### PR TITLE
Improved the about Page #20

### PR DESCRIPTION
**Pull request by anubhav1206**

### CODE REVIEW

**Review by Abhilekhgautam — CHANGES_REQUESTED** [review]
I'd want few changes before this could be merged.
1. Could you center the image: 
image

2. The gap between `objectives` and `open for all` subtopics is preety large, could you reduce the gap.
image

3. Looks like there is a typo under our objectives section, it should be `opensource` instead of `opeh3source`.
4. The `our objective` header could be made `h2`.

Everything else looks fine to me.

**Comment by anubhav1206** [comment]
sure I will

**Comment by anubhav1206** [comment]
Kindly check

**Comment by Abhilekhgautam** [comment]
Your request will only be merged if the requested changes are applied.

**Pull request closed without merging**
