### PR TITLE
CSS on nav-link, More about us button and social media 

### PR DESCRIPTION
**Pull request by iam8uman**
Added css to make more attractive aba merge garihalda ramro!

### CODE REVIEW

**Comment by bishalx0** [comment]
Hello @iam8uman 
It would be better if you made some corrections mentioned below, 

1. Here in the button, bg is more on the left and the hover effect is more on the right
so please make it properly aligned

image

2. Also, I would appreciate adding the same effect on other pages like About, contact, etc. as there are no such effects.

image

**Comment by iam8uman** [comment]
I am sending you a video that looks so perfect But I don't why in the website does not look like this. I think it is taking time to synchronize.

**Comment by bishalx0** [comment]
> I am sending you a video that looks so perfect But I don't why in the website does not look like this. I think it is taking time to synchronize.

Okey, I will see

**Comment by mukezhz** [comment]
@iam8uman 
Thank you for the PR and sorry for the late review

**Pull request merged**
